# Generated by Django 4.2.3 on 2023-07-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='contact',
            field=models.CharField(max_length=170, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(max_length=170, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='pic',
            field=models.ImageField(null=True, upload_to='user'),
        ),
    ]
