# Generated by Django 4.2.3 on 2023-07-07 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0002_myuser_contact_myuser_name_myuser_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
    ]
